name: supply
channels:
  - conda-forge
  - defaults
dependencies:
  - absl-py=2.3.1
  - altair=5.5.0
  - appnope=0.1.4
  - arrow-cpp=21.0.0
  - asttokens=3.0.0
  - attrs=25.4.0
  - aws-c-auth=0.9.0
  - aws-c-cal=0.9.2
  - aws-c-common=0.12.4
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.6
  - aws-c-http=0.10.4
  - aws-c-io=0.21.4
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.8.7
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.34.0
  - aws-sdk-cpp=1.11.638
  - blinker=1.9.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.10.5
  - cachetools=6.2.1
  - certifi=2025.10.5
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - click=8.3.0
  - comm=0.2.3
  - contourpy=1.3.3
  - cycler=0.12.1
  - debugpy=1.8.17
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - fonttools=4.60.1
  - freetype=2.14.1
  - gflags=2.2.2
  - gitdb=4.0.12
  - gitpython=3.1.45
  - glog=0.5.0
  - h2=4.3.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - idna=3.11
  - importlib-metadata=8.7.0
  - ipykernel=7.1.0
  - ipython=9.6.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jinja2=3.1.6
  - jsonschema=4.25.1
  - jsonschema-specifications=2025.9.1
  - jupyter_client=8.6.3
  - jupyter_core=5.9.1
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lcms2=2.17
  - lerc=4.0.0
  - libabseil=20250127.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=8.16.0
  - libcxx=21.1.4
  - libdeflate=1.24
  - libedit=3.1.20250104
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgrpc=1.71.0
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnghttp2=1.67.0
  - libopenblas=0.3.30
  - libpng=1.6.50
  - libprotobuf=5.29.3
  - libre2-11=2024.07.02
  - libsodium=1.0.20
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libthrift=0.15.0
  - libtiff=4.7.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libzlib=1.3.1
  - llvm-openmp=21.1.4
  - lz4-c=1.9.4
  - markupsafe=3.0.3
  - matplotlib=3.10.7
  - matplotlib-base=3.10.7
  - matplotlib-inline=0.2.1
  - munkres=1.1.4
  - narwhals=2.10.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nomkl=1.0
  - numpy=2.3.4
  - openjpeg=2.5.4
  - openssl=3.5.4
  - orc=2.2.0
  - packaging=25.0
  - pandas=2.3.3
  - parso=0.8.5
  - patsy=1.0.2
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=12.0.0
  - pip=25.2
  - platformdirs=4.5.0
  - plotly=6.3.1
  - prompt-toolkit=3.0.52
  - psutil=7.1.2
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyarrow=21.0.0
  - pycparser=2.22
  - pydeck=0.9.1
  - pygments=2.19.2
  - pyparsing=3.2.5
  - pysocks=1.7.1
  - python=3.11.0
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.11
  - pytz=2025.2
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - qhull=2020.2
  - re2=2024.07.02
  - readline=8.2
  - referencing=0.37.0
  - requests=2.32.5
  - rpds-py=0.28.0
  - scipy=1.16.3
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=80.9.0
  - six=1.17.0
  - smmap=5.0.2
  - snappy=1.2.2
  - stack_data=0.6.3
  - statsmodels=0.14.5
  - streamlit=1.51.0
  - tenacity=9.1.2
  - tk=8.6.13
  - toml=0.10.2
  - tornado=6.5.2
  - traitlets=5.14.3
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - unicodedata2=16.0.0
  - urllib3=2.5.0
  - utf8proc=2.6.1
  - watchdog=6.0.0
  - wcwidth=0.2.14
  - wheel=0.45.1
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zlib-ng=2.2.5
  - zstandard=0.25.0
  - zstd=1.5.7
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - black==25.9.0
      - cython==3.1.6
      - decorator==4.4.2
      - filelock==3.20.0
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - isort==7.0.0
      - joblib==1.5.2
      - mpmath==1.3.0
      - multidict==6.7.0
      - mypy-extensions==1.1.0
      - networkx==3.5
      - pathspec==0.12.1
      - propcache==0.4.1
      - protobuf==6.33.0
      - pyg-lib==0.5.0+pt28
      - pytokens==0.3.0
      - scikit-learn==1.7.2
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - torch==2.8.0
      - torch-cluster==1.6.3
      - torch-geometric==2.7.0
      - torch-geometric-temporal==0.56.2
      - torch-scatter==2.1.2
      - torch-sparse==0.6.18
      - torch-spline-conv==1.2.2
      - torchaudio==2.8.0
      - torchvision==0.23.0
      - tqdm==4.67.1
      - xxhash==3.6.0
      - yarl==1.22.0
prefix: /Users/ed_aguilar/miniconda3/envs/supply
